Vagrant::Config.run do |config|
  config.vm.box = "base"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port "http", 80, 8080

  config.vm.provision :puppet do |puppet|
    puppet.module_path    = "../../"
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "base.pp"
    puppet.options        = "--verbose"
  end

end
